RoleName: ManagedServiceRole
ZoneId: ap-southeast-1a
VpcId: vpc-t4nb2um7p8kn8y95a4cj9
ServiceType: managed
VSwitchId: vsw-t4n3xdn0ev4neg0pznsbg
ArtifactSourceType: DockerCompose
ServiceBuildRegion: ap-southeast-1
RepoName: linziqiaolzq/quickstart-langflow
DockerComposeEnvPath: .env
RegionId: ap-southeast-1
CustomParameters: ''
DockerComposeYamlPath: docker-compose.yml
Owner: linziqiaolzq
Branch: test
Platform: github
