RoleName: ManagedServiceRole
ZoneId: ap-southeast-1a
VpcId: vpc-t4n7bphse0i27gqvcfj87
ServiceType: managed
VSwitchId: vsw-t4nfdzhjq5vwzrt0veoa8
ArtifactSourceType: DockerCompose
ServiceBuildRegion: ap-southeast-1
RepoName: linziqiaolzq/quickstart-langflow
DockerComposeEnvPath: .env
RegionId: ap-southeast-1
CustomParameters: ''
DockerComposeYamlPath: docker-compose.yml
Owner: linziqiaolzq
Branch: test
Platform: github
